import json,pathlib,subprocess,hashlib,datetime,os,time
R=pathlib.Path('/Users/earlcameron/Desktop/dungeonflux');E=R/'development/evidence/contracts-g03/integration';B=R/'artifacts/build/contracts-g03-integration-review';S=R/'artifacts/tmp/CONTRACT-G03-001-integration-review';C='9898c70614a8555efa63d3cec47ba9adbc395bbb';load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();put=lambda n,x:(E/n).write_text(json.dumps(x,indent=2)+'\n');env=os.environ.copy();env.update(DUNGEONFLUX_ARTIFACT_ROOT=str(R/'artifacts'),DUNGEONFLUX_BUILD_ROOT=str(B),DUNGEONFLUX_TMP_ROOT=str(S),CARGO_NET_OFFLINE='true');results=[]
def run(n,a,expected=0):
 t=time.monotonic()
 with (E/(n+'.stdout')).open('wb') as out,(E/(n+'.stderr')).open('wb') as err:
  p=subprocess.run(list(map(str,a)),cwd=R,env=env,stdout=out,stderr=err,timeout=600)
 x={'name':n,'argv':list(map(str,a)),'cwd':str(R),'environment':{k:env[k] for k in ['DUNGEONFLUX_ARTIFACT_ROOT','DUNGEONFLUX_BUILD_ROOT','DUNGEONFLUX_TMP_ROOT','CARGO_NET_OFFLINE']},'exit_code':p.returncode,'expected':expected,'seconds':round(time.monotonic()-t,3),'passed':p.returncode==expected,'stdout_sha256':sha(E/(n+'.stdout')),'stderr_sha256':sha(E/(n+'.stderr'))};results.append(x);put('commands.json',results);print(n,p.returncode,flush=True);assert x['passed'];return (E/(n+'.stdout')).read_bytes()
src=load(E.parent/'worker/source-identity.json');protect=load(R/'development/evidence/cleanup-009/independent-boundary.json')['protected_binary_hashes'];candidate=load(E.parent/'review/post-gates-artifacts.json');ident={'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source':{p:{'sha256':sha(R/p),'worker_sha256':h,'git_blob_match':subprocess.check_output(['git','show',C+':'+p],cwd=R)==(R/p).read_bytes()} for p,h in src['source_sha256'].items()},'protected_before':{i['path']:sha(R/i['path']) for i in protect},'candidate_after_review_before_integration':{i['path']:sha(i['path']) for i in candidate}};assert all(i['sha256']==i['worker_sha256'] and i['git_blob_match'] for i in ident['source'].values());assert all(sha(R/i['path'])==i['sha256'] for i in protect);put('identity.json',ident)
assert run('main-head',['git','rev-parse','HEAD']).decode().strip()==C
assert not run('application-clean',['git','status','--porcelain','--','Cargo.toml','Cargo.lock','rust-toolchain.toml','.cargo','crates','development/build-fixture.sh']).strip()
w=R/'development/build-fixture.sh'
run('main-fmt',[w,'cargo','fmt','--all','--','--check'])
run('main-contract-tests',[w,'cargo','test','--locked','--offline','--jobs','1','-p','df-tools','--test','shared_contracts','--test','schema_ledger','--','--test-threads=1'])
run('main-native-build',[w,'cargo','build','--locked','--offline','--jobs','1','-p','df-tools','--bin','df-transport-fixture'])
run('main-wasm-build',[w,'cargo','build','--locked','--offline','--jobs','1','-p','df-tools','--lib','--target','wasm32-unknown-unknown'])
for target in ['aarch64-apple-darwin','wasm32-unknown-unknown']:
 for crate in ['df-types','df-protocol']:run('tree-'+crate+'-'+target,[w,'cargo','tree','--locked','--offline','--target',target,'-p',crate,'--edges','normal'])
run('historical-audit-stale',['/Users/earlcameron/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',R/'development/dependency-audit.py'],1)
paths=[B/'debug/df-transport-fixture',B/'wasm32-unknown-unknown/debug/df_tools.wasm']
for p in (B/'debug/deps').iterdir():
 if p.name.startswith(('shared_contracts-','schema_ledger-')) and p.suffix=='':paths.append(p)
ident['new_artifacts']=[{'path':str(p),'sha256':sha(p),'bytes':p.stat().st_size,'embedded_source_revision':C.encode() in p.read_bytes()} for p in paths];ident['descriptors']=[{'path':str(p),'sha256':sha(p)} for p in B.glob('**/out/contracts.bin')];assert len(ident['descriptors'])>=2 and all(x['sha256']=='f524d0403f03bc9a5a975d7a6c54e3d3c9f5542e9351be3c8ecf869579a8b560' for x in ident['descriptors']);assert all(x['embedded_source_revision'] for x in ident['new_artifacts'][:2]);ident['protected_after']={i['path']:sha(R/i['path']) for i in protect};ident['candidate_after_integration']={i['path']:sha(i['path']) for i in candidate};assert ident['protected_before']==ident['protected_after'] and ident['candidate_after_review_before_integration']==ident['candidate_after_integration'];ident['application_clean_after']=not run('application-clean-after',['git','status','--porcelain','--','Cargo.toml','Cargo.lock','rust-toolchain.toml','.cargo','crates','development/build-fixture.sh']).strip();put('identity.json',ident);print('ALL MAIN CHECKS PASS',flush=True)
