[package]
name = "df-display"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
df-client = { path = "../df-client" }
df-protocol = { path = "../df-protocol" }
df-types = { path = "../df-types" }
df-ui = { path = "../df-ui" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = ["Window", "Document", "Element", "Node", "HtmlElement", "HtmlFieldSetElement", "HtmlButtonElement", "Event", "EventTarget", "HtmlImageElement"] }
