pub(crate) const STYLESHEET: &str = r#"
.df-session-phase{--gold:#dfb974;--ink:#070d14;--text:#f5eee0;--muted:#b6bec6;color:var(--text);background:var(--ink);font:16px/1.6 Georgia,'Times New Roman',serif;min-height:100svh;overflow-wrap:anywhere;padding:clamp(18px,4vw,64px);box-sizing:border-box}
.df-session-phase *{box-sizing:border-box;min-width:0}.df-session-phase [hidden]{display:none!important}.df-session-phase .session-header{max-width:1200px;margin:auto;position:relative;padding-bottom:28px;border-bottom:1px solid #dfb97455}.df-session-phase .session-brand,.df-session-phase .bookend-kind{font:11px/1.6 system-ui,sans-serif;letter-spacing:2px;text-transform:uppercase;color:var(--gold)}
.df-session-phase h1{font-size:clamp(34px,5vw,64px);line-height:1.15;font-weight:400;margin:14px 0}.df-session-phase h2{font-size:clamp(24px,3vw,35px);font-weight:400;line-height:1.25;margin:15px 0}.df-session-phase .session-subtitle{color:var(--muted);max-width:700px}.df-session-phase button{min-height:44px;padding:11px 18px;border:1px solid #bba06b88;border-radius:4px;color:#f3d59d;background:#142330;font:14px/1.5 system-ui,sans-serif;cursor:pointer}.df-session-phase button:disabled{color:#8d9aa7;border-color:#8895a644;cursor:default}.df-session-phase button:focus-visible,.df-session-phase input:focus-visible{outline:3px solid #9ddbff;outline-offset:4px}
.df-session-phase .session-recovery{max-width:1200px;margin:24px auto;background:#101d29;border:1px solid #a0aeb13a;padding:18px 24px;border-radius:4px}.df-session-phase .connection-label{font:14px/1.5 system-ui,sans-serif;color:#b8dfc7;margin:0}.df-session-phase[data-session-connection=reconnecting] .connection-label,.df-session-phase[data-session-connection=offline] .connection-label{color:#f3cd90}.df-session-phase .connection-detail{font:13px/1.6 system-ui,sans-serif;color:var(--muted);margin:8px 0}.df-session-phase .df-ui-panel{border-top:1px solid #c5b18a33;padding-top:10px}.df-session-phase [role=alert]{color:#ffbdad}.df-session-phase .df-ui-feedback{font:14px/1.6 system-ui,sans-serif;margin:8px 0;overflow-wrap:anywhere}
.df-session-phase .session-essential{max-width:1200px;margin:24px auto}.df-session-phase .session-essential input{width:100%;padding:14px;min-height:44px;background:#0c1721;color:var(--text);border:1px solid #a0aeb16b;font:16px/1.5 system-ui,sans-serif;border-radius:4px}.df-session-phase .session-drawer{max-width:1200px;margin:24px auto;padding:24px;border:1px solid #cbb27b66;background:#0d1824;border-radius:5px;box-shadow:0 24px 80px #0005;animation:session-arrive .18s ease-out}.df-session-phase .session-drawer>button{display:block;margin-left:auto}.df-session-phase .session-bookend{margin:24px 0;background:#09121c;border:1px solid #bda16844;overflow:hidden}.df-session-phase .session-still{display:block;width:100%;height:clamp(160px,36vw,420px);object-fit:cover;background:linear-gradient(130deg,#162734,#08101a);color:var(--muted)}.df-session-phase .bookend-copy{padding:clamp(18px,3vw,36px);background:linear-gradient(115deg,#131f2c,#08121d)}.df-session-phase .bookend-context{color:var(--muted);font:14px/1.7 system-ui,sans-serif;max-width:800px}.df-session-phase .bookend-caption{font-size:clamp(18px,2.3vw,27px);line-height:1.6;margin:25px 0;padding-left:22px;border-left:2px solid var(--gold);max-width:900px}.df-session-phase .bookend-attribution,.df-session-phase .bookend-position{font:12px/1.7 system-ui,sans-serif;color:var(--muted)}.df-session-phase .session-host{border-top:1px solid #bda16844;padding-top:18px}.df-session-phase .session-host p{color:var(--muted);font:14px/1.7 system-ui,sans-serif}.df-session-phase .session-host button{margin:4px 12px 4px 0}.df-session-phase .session-local-error{max-width:1200px;margin:auto;font:14px/1.6 system-ui,sans-serif}
@keyframes session-arrive{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}.df-session-phase[data-reduced-motion=true] .session-drawer{animation:none}
@media(prefers-reduced-motion:reduce){.df-session-phase .session-drawer{animation:none}}@media(max-width:600px){.df-session-phase{padding:18px}.df-session-phase .session-drawer{padding:14px}.df-session-phase .session-recovery{padding:16px}.df-session-phase .session-host button{width:100%;margin:6px 0}.df-session-phase .bookend-caption{padding-left:14px}.df-session-phase .session-still{height:200px}}
"#;
